/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nay_HsPerfDataParser */

#ifndef _Included_org_nay_HsPerfDataParser
#define _Included_org_nay_HsPerfDataParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_nay_HsPerfDataParser
 * Method:    parseHsPerfDataFromFile
 * Signature: (Ljava/lang/String;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_org_nay_HsPerfDataParser_parseHsPerfDataFromFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
